# Generated by Django 3.2.3 on 2021-08-19 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0003_alter_prestamo_libro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Lector', 'verbose_name_plural': 'Lectores'},
        ),
    ]
