# Generated by Django 3.2.3 on 2021-08-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_alter_autor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombres'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.RemoveField(
            model_name='autor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='nombre',
        ),
        migrations.AddField(
            model_name='autor',
            name='apellidos',
            field=models.CharField(default='autor', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='nombres',
            field=models.CharField(default='autor', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
