# Generated by Django 3.2.3 on 2021-08-19 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0003_auto_20210817_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={},
        ),
        migrations.RemoveField(
            model_name='autor',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='nombres',
        ),
    ]
