# Generated by Django 3.2.3 on 2021-08-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0004_auto_20210818_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AddField(
            model_name='autor',
            name='apellidos',
            field=models.CharField(default='n', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(default='ape', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='nombres',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
