# Generated by Django 3.2.3 on 2021-08-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0005_auto_20210818_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='seudonimo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='seudonimo'),
        ),
    ]
