# Generated by Django 3.0.4 on 2021-10-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_entry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Entry', verbose_name='Imagen'),
        ),
    ]
